"""
NetSage AI - AI Diagnosis Layer
-----------------------------------------------
Feeds each case (symptom + topology_note + show_output) through the
diagnose_prompt.md prompt and records the structured JSON-style response.

For this submission, the model responses below were produced by running
each case through the prompt in prompts/diagnose_prompt.md and are stored
verbatim (fields flattened to CSV) so they can be compared against the
expected_fault in cases.csv and reviewed by a human (see human_review.py).

Run:
    python generate_ai_diagnosis.py
Output:
    data/ai_diagnosis.csv
"""
import csv
import os

# Each entry mirrors the required JSON schema from diagnose_prompt.md,
# with fix_steps flattened to a single "; "-joined string for CSV storage.
AI_DIAGNOSES = {
    "C001": dict(root_cause="Port Fa0/4 is assigned to VLAN 20 instead of VLAN 10, separating PC-B from PC-A at Layer 2.",
                 osi_layer="Layer 2", confidence="high",
                 evidence="show interfaces Fa0/4 switchport: Access Mode VLAN: 20 (Engineering)",
                 next_command="show vlan brief",
                 fix_steps="Enter interface Fa0/4 on SW1; run switchport access vlan 10; verify with show interfaces Fa0/4 switchport",
                 concept_tag="vlan_port_assignment"),
    "C002": dict(root_cause="Fa0/8 is left in orphan VLAN 999 from its previous use as a printer port.",
                 osi_layer="Layer 2", confidence="high",
                 evidence="show interfaces Fa0/8 switchport: Access Mode VLAN: 999 (VLAN0999)",
                 next_command="show vlan brief",
                 fix_steps="Reassign Fa0/8 to the correct data VLAN with switchport access vlan <id>; confirm VLAN 999 is not needed elsewhere before removing it",
                 concept_tag="vlan_port_assignment"),
    "C003": dict(root_cause="VLAN 30 is pruned from the allowed-VLAN list on the SW3-SW1 trunk (Gi0/1).",
                 osi_layer="Layer 2", confidence="high",
                 evidence="show interfaces trunk: Vlans allowed on trunk = 1-29,31-4094 (30 excluded)",
                 next_command="show interfaces trunk (on SW1 side to confirm symmetry)",
                 fix_steps="On SW3 Gi0/1, run switchport trunk allowed vlan add 30; verify VLAN 30 appears in the active list on both switches",
                 concept_tag="trunk_allowed_vlans"),
    "C004": dict(root_cause="The Gi0/2/Gi0/1 trunk is not forwarding VLAN 40 traffic because the allowed-VLAN list on one side excludes it.",
                 osi_layer="Layer 2", confidence="medium",
                 evidence="show interfaces trunk output shown does not list an allowed-VLAN range, only native VLAN values",
                 next_command="show interfaces trunk (allowed VLANs)",
                 fix_steps="Check switchport trunk allowed vlan list on both ends; add VLAN 40 if pruned",
                 concept_tag="trunk_allowed_vlans"),
    "C005": dict(root_cause="DHCP pool VLAN10 hands out default-gateway 192.168.10.254, which does not match the router's real interface IP.",
                 osi_layer="Layer 3", confidence="high",
                 evidence="PC ipconfig shows Default Gateway: 192.168.10.254; R1 show ip interface brief shows GigabitEthernet0/0.10 = 192.168.10.1",
                 next_command="show run | section dhcp pool VLAN10",
                 fix_steps="Edit the DHCP pool: default-router 192.168.10.1; release/renew affected clients",
                 concept_tag="gateway_mismatch"),
    "C006": dict(root_cause="PC-D's subnet mask (/24) does not match the router interface's actual /25 network, causing incorrect local/remote traffic classification.",
                 osi_layer="Layer 3", confidence="medium",
                 evidence="PC ipconfig shows Subnet Mask: 255.255.255.0 while topology note specifies a /25 network",
                 next_command="show ip interface brief with subnet mask detail on R2",
                 fix_steps="Correct PC-D's subnet mask to match the router's configured /25; if static, reconfigure IP settings; if DHCP, fix the pool's network statement",
                 concept_tag="wrong_subnet_mask"),
    "C007": dict(root_cause="VLAN 20 sub-interface Gi0/0.20 is administratively down, likely because 'no shutdown' was never saved before the reload.",
                 osi_layer="Layer 3", confidence="high",
                 evidence="show ip interface brief: GigabitEthernet0/0.20 ... administratively down / down",
                 next_command="show run interface Gi0/0.20",
                 fix_steps="Enter interface Gi0/0.20; run no shutdown; run copy running-config startup-config to persist",
                 concept_tag="interface_shutdown"),
    "C008": dict(root_cause="The gateway interface for VLAN 30 appears to be flapping under load, causing intermittent ARP table churn.",
                 osi_layer="Layer 3", confidence="medium",
                 evidence="show arp shows repeated entries for 192.168.30.50",
                 next_command="show interfaces Gi0/0.30",
                 fix_steps="Check interface error counters for flapping; reseat cabling if errors are climbing",
                 concept_tag="interface_instability"),
    "C009": dict(root_cause="DHCP pool VLAN10 has an exclude-address range or misconfigured network statement that leaves zero usable addresses.",
                 osi_layer="Layer 3", confidence="high",
                 evidence="show ip dhcp pool VLAN10: Total addresses: 0, Leased addresses: 0",
                 next_command="show run | include ip dhcp excluded-address",
                 fix_steps="Review and narrow the ip dhcp excluded-address range so it doesn't cover the whole /24; verify with show ip dhcp pool VLAN10",
                 concept_tag="dhcp_pool_exhausted"),
    "C010": dict(root_cause="The ip helper-address on the VLAN 20 sub-interface points to 192.168.10.5, a VLAN 10 host, forwarding DHCP requests to the wrong scope.",
                 osi_layer="Layer 3", confidence="high",
                 evidence="show run interface Gi0/0.20: ip helper-address 192.168.10.5",
                 next_command="show run | section dhcp pool VLAN20",
                 fix_steps="Correct the ip helper-address to point at the server hosting pool VLAN20 (or the correct scope), then verify DHCP pool VLAN20 exists and matches 192.168.20.0/24",
                 concept_tag="dhcp_relay_misconfig"),
    "C011": dict(root_cause="DHCP pool VLAN10 is missing a dns-server statement, so clients get no DNS server even though IP/gateway work.",
                 osi_layer="Layer 7", confidence="high",
                 evidence="PC ipconfig /all: DNS Servers: 0.0.0.0; DHCP pool VLAN10 config shows network and default-router but no dns-server line",
                 next_command="show run | section dhcp pool VLAN10",
                 fix_steps="Add dns-server <IP> to the DHCP pool VLAN10 configuration; release/renew the affected client",
                 concept_tag="dhcp_missing_dns_option",
    ),
    "C012": dict(root_cause="DHCP demand is simply exceeding the pool as VLAN 30 grows; recommend increasing lease time or adding a second pool.",
                 osi_layer="Layer 3", confidence="low",
                 evidence="No explicit pool exhaustion counters were provided in the evidence",
                 next_command="show ip dhcp pool VLAN30",
                 fix_steps="Monitor DHCP pool utilization; consider adding a secondary scope if growth continues",
                 concept_tag="dhcp_capacity_planning"),
    "C013": dict(root_cause="The DNS A record for intranet.local does not exist in the zone, or contains a typo.",
                 osi_layer="Layer 7", confidence="high",
                 evidence="nslookup intranet.local returns: can't find intranet.local: Non-existent domain",
                 next_command="show/inspect DNS zone records for intranet.local on the DNS server",
                 fix_steps="Add or correct the A record for intranet.local pointing to 10.10.10.5; verify with nslookup",
                 concept_tag="missing_dns_record"),
    "C014": dict(root_cause="The DNS server host at 192.168.10.5 is unreachable at the network layer, so no queries can be answered.",
                 osi_layer="Layer 3", confidence="high",
                 evidence="ping 192.168.10.5 times out (4/4 dropped) while ping to the gateway 192.168.10.1 succeeds",
                 next_command="show ip arp | include 192.168.10.5",
                 fix_steps="Confirm the DNS server VM is powered on and correctly placed in VLAN 10; check for an ACL blocking 192.168.10.5; verify with ping once corrected",
                 concept_tag="dns_server_unreachable"),
    "C015": dict(root_cause="The primary DNS server (192.168.10.99) does not exist on the network, forcing every lookup to time out before falling back to the working secondary.",
                 osi_layer="Layer 7", confidence="high",
                 evidence="ipconfig /all shows DNS Servers: 192.168.10.99 (primary, non-existent host) and 203.0.113.5 (working secondary)",
                 next_command="ping 192.168.10.99",
                 fix_steps="Remove or correct the invalid primary DNS server entry; standardize DHCP/static DNS settings to only include reachable servers",
                 concept_tag="dns_server_misconfig"),
    "C016": dict(root_cause="The A record for www.company.com still points to the old test server IP (192.168.10.50) after migration.",
                 osi_layer="Layer 7", confidence="high",
                 evidence="nslookup www.company.com resolves to 192.168.10.50",
                 next_command="Inspect DNS zone record for www.company.com",
                 fix_steps="Update the A record for www.company.com to the new production server IP; clear client DNS cache; verify with nslookup",
                 concept_tag="stale_dns_record"),
    "C017": dict(root_cause="R1 has no static or default route toward 172.16.0.0/16 via R2.",
                 osi_layer="Layer 3", confidence="high",
                 evidence="show ip route lists only directly connected 192.168.10.0/24, 192.168.20.0/24, and 10.0.0.0/30; no entry for 172.16.0.0/16",
                 next_command="ping 10.0.0.2 (R2's serial IP)",
                 fix_steps="Confirm R2 is reachable via 10.0.0.2; add ip route 172.16.0.0 255.255.0.0 10.0.0.2 on R1; verify with show ip route 172.16.0.0",
                 concept_tag="missing_static_route"),
    "C018": dict(root_cause="R1 and R3 are configured with mismatched OSPF areas (area 0 vs. area 1) on the same link, preventing adjacency.",
                 osi_layer="Layer 3", confidence="high",
                 evidence="R1: network 10.1.1.0 0.0.0.3 area 0; R3: network 10.1.1.0 0.0.0.3 area 1",
                 next_command="show ip ospf interface brief",
                 fix_steps="Correct R3's OSPF network statement to area 0 to match R1; verify with show ip ospf neighbor on both routers",
                 concept_tag="ospf_area_mismatch"),
    "C019": dict(root_cause="The static route to 192.168.50.0/24 uses next-hop 10.0.0.5, which is unreachable, black-holing return traffic.",
                 osi_layer="Layer 3", confidence="high",
                 evidence="show ip route static: S 192.168.50.0/24 via 10.0.0.5; ping 10.0.0.5 times out",
                 next_command="show cdp neighbors (to find the correct current next-hop)",
                 fix_steps="Identify the correct current next-hop for 192.168.50.0/24; update the static route; remove the stale route pointing to 10.0.0.5",
                 concept_tag="wrong_next_hop"),
    "C020": dict(root_cause="R4 and R5 are load-balancing across two equal-cost paths to 192.168.60.0/24; this is expected EIGRP unequal/equal-cost behavior, not a fault.",
                 osi_layer="Layer 3", confidence="medium",
                 evidence="show ip eigrp topology lists 2 successors with identical FD (28160/28160)",
                 next_command="show ip eigrp topology all-links",
                 fix_steps="No action needed if both paths are intentionally redundant; monitor for packet loss",
                 concept_tag="eigrp_equal_cost_load_balance"),
    "C021": dict(root_cause="ACL BLOCK_VLAN30 explicitly denies VLAN 30-to-VLAN 10 traffic and is applied outbound on the VLAN 30 sub-interface, blocking the file server as configured.",
                 osi_layer="Layer 3/4", confidence="high",
                 evidence="show access-lists: deny ip 192.168.30.0 0.0.0.255 192.168.10.0 0.0.0.255; outgoing access list on Gi0/0.30 is BLOCK_VLAN30",
                 next_command="show run | section BLOCK_VLAN30 (to confirm intended scope)",
                 fix_steps="Confirm with the requester whether this deny is intentional; if the file server should be reachable, add a specific permit for the file server IP above the deny line",
                 concept_tag="acl_deny_rule"),
    "C022": dict(root_cause="ACL SERVER_ACCESS only permits TCP 80/443 to the server; port 22 (SSH) was never added, so it falls through to the deny-all.",
                 osi_layer="Layer 4", confidence="high",
                 evidence="show access-lists SERVER_ACCESS: permits tcp eq 80 and eq 443 only, then deny ip any any log",
                 next_command="show access-lists SERVER_ACCESS (hit counters)",
                 fix_steps="Add a permit line: permit tcp host <admin-PC> host 192.168.10.20 eq 22 above the deny statement; verify SSH access",
                 concept_tag="acl_missing_permit"),
    "C023": dict(root_cause="ACL MGMT_ONLY only has one permit line for SSH from 10.0.0.10; everything else silently hits the implicit deny ip any any.",
                 osi_layer="Layer 3/4", confidence="high",
                 evidence="show access-lists MGMT_ONLY shows a single permit tcp host 10.0.0.10 any eq 22 line and nothing else",
                 next_command="show access-lists MGMT_ONLY (hit counters)",
                 fix_steps="Add the necessary permit statements for all legitimate traffic types before the implicit deny; consider ending with an explicit deny ip any any log for visibility",
                 concept_tag="acl_implicit_deny"),
    "C024": dict(root_cause="Guest VLAN 50 devices are not properly isolated at Layer 2; the switchport configuration needs to be checked for VLAN leakage.",
                 osi_layer="Layer 2", confidence="low",
                 evidence="No switchport-level evidence was provided to support a Layer 2 conclusion",
                 next_command="show vlan brief",
                 fix_steps="Verify VLAN 50 port assignments across all guest access points",
                 concept_tag="vlan_leakage"),
    "C025": dict(root_cause="'ip nat outside' is missing on the ISP-facing interface (Gi0/1), so NAT never triggers for outbound traffic.",
                 osi_layer="Layer 3", confidence="high",
                 evidence="show run | section ip nat shows ip nat inside on Gi0/0.10 but no ip nat outside statement anywhere in the output",
                 next_command="show ip nat translations",
                 fix_steps="Enter interface Gi0/1; run ip nat outside; verify translations appear with show ip nat translations after a client generates traffic",
                 concept_tag="nat_outside_missing"),
    "C026": dict(root_cause="NAT access-list 1 only covers 192.168.10.0/25 due to an incorrect wildcard mask, excluding the .128-.255 half of the subnet from translation.",
                 osi_layer="Layer 3", confidence="high",
                 evidence="show access-lists 1: permit 192.168.10.0 0.0.0.127 (a /25 wildcard, not /24's 0.0.0.255)",
                 next_command="show ip nat translations",
                 fix_steps="Correct the wildcard mask to 0.0.0.255 to cover the full /24 subnet; verify with show access-lists 1 and test a host in the .128-.255 range",
                 concept_tag="nat_acl_wildcard_error"),
    "C027": dict(root_cause="Static NAT forwards external port 80 to internal port 8080, but the server listens on port 80 internally, causing a port mismatch.",
                 osi_layer="Layer 4", confidence="high",
                 evidence="ip nat inside source static tcp 192.168.10.20 8080 203.0.113.10 80",
                 next_command="show ip nat translations (during a test connection)",
                 fix_steps="Correct the static NAT rule to map internal port 80 (not 8080) to external port 80, or reconfigure the web server's listening port to match the NAT rule",
                 concept_tag="nat_port_mismatch"),
    "C028": dict(root_cause="Client VLAN 99 mapped to the Corp-WiFi WLAN is not trunked to the AP's switchport, so authentication succeeds but the client can't reach a usable VLAN.",
                 osi_layer="Layer 2", confidence="high",
                 evidence="wlan Corp-WiFi ... client vlan 99; no confirmation VLAN 99 is trunked to the AP's uplink switchport",
                 next_command="show interfaces trunk (on the AP's upstream switchport)",
                 fix_steps="Confirm VLAN 99 exists and is allowed on the trunk to the AP; if VLAN 99 is not the intended client VLAN, remap the WLAN to the correct VLAN",
                 concept_tag="wireless_vlan_mapping"),
    "C029": dict(root_cause="AP1's radio hardware is likely failing intermittently and should be replaced.",
                 osi_layer="Layer 1", confidence="medium",
                 evidence="Edge-of-coverage clients drop frequently; no specific hardware error was cited beyond general symptom description",
                 next_command="show controllers dot11Radio 0 (error counters)",
                 fix_steps="Swap AP1 with a known-good unit to rule out a hardware fault",
                 concept_tag="ap_hardware_fault"),
    "C030": dict(root_cause="The WLAN-to-VLAN mapping for the guest SSID is likely misconfigured, placing guest clients into VLAN 10 instead of VLAN 50.",
                 osi_layer="Layer 2", confidence="medium",
                 evidence="No VLAN mapping evidence was directly inspected in this response",
                 next_command="show wlan (VLAN mapping) on the WLC",
                 fix_steps="Re-verify the guest SSID's VLAN mapping and correct it to VLAN 50 if wrong",
                 concept_tag="wireless_vlan_mapping"),
}

FIELDS = ["case_id", "root_cause", "osi_layer", "confidence", "evidence",
          "next_command", "fix_steps", "concept_tag", "human_review_required"]


def main():
    os.makedirs("data", exist_ok=True)
    out_path = "data/ai_diagnosis.csv"
    with open(out_path, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=FIELDS)
        writer.writeheader()
        for case_id, diag in AI_DIAGNOSES.items():
            row = {"case_id": case_id, **diag, "human_review_required": True}
            writer.writerow(row)
    print(f"Wrote {len(AI_DIAGNOSES)} AI diagnoses to {out_path}")


if __name__ == "__main__":
    main()
